#!/bin/bash
# Dynamically generate a bind mount for Claude Code conversation history
# Runs on the host as the devcontainer initializeCommand
CLAUDE_PROJECT_DIR="$HOME/.claude/projects/$(pwd | sed 's/[^a-zA-Z0-9]/-/g')"

if [ -d "$CLAUDE_PROJECT_DIR" ]; then
  cat > "$(dirname "$0")/docker-compose.claude.yml" << EOF
# Auto-generated by init-claude.sh (gitignored)
# Bind mount to share Claude Code conversation history with the Dev Container
services:
  backend:
    volumes:
      - ${CLAUDE_PROJECT_DIR}:/root/.claude/projects/-app
EOF
  echo "[init-claude] Claude history mount: ${CLAUDE_PROJECT_DIR}"
else
  cat > "$(dirname "$0")/docker-compose.claude.yml" << 'EOF'
# Auto-generated by init-claude.sh (gitignored)
# Skipped because no Claude Code project directory was found
services: {}
EOF
  echo "[init-claude] No Claude project directory found, skipping history mount"
fi
