/** Query keys dedicated to SSE streams.
 *
 * Query keys for REST APIs are auto-generated by orval (getXxxQueryKey).
 * This module only defines keys for data written directly into the cache via SSE.
 */

export const sseKeys = {
  topicStats: () => ["sse", "topic-stats"] as const,
  logs: () => ["sse", "logs"] as const,
  connectionStatus: () => ["sse", "connection-status"] as const,
  jobs: () => ["sse", "jobs"] as const,
};
